//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoKatalog.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoKatalog.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream close5 {
            get {
                return ResourceManager.GetStream("close5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;year=.
        /// </summary>
        internal static string earningsPostfix {
            get {
                return ResourceManager.GetString("earningsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.worldwideboxoffice.com/movie.cgi?title=.
        /// </summary>
        internal static string earningsPrefix {
            get {
                return ResourceManager.GetString("earningsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenCheck50p {
            get {
                object obj = ResourceManager.GetObject("greenCheck50p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imdb30p {
            get {
                object obj = ResourceManager.GetObject("imdb30p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /business.
        /// </summary>
        internal static string imdbPostfixBudget {
            get {
                return ResourceManager.GetString("imdbPostfixBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episodes?season=.
        /// </summary>
        internal static string imdbPostfixEpisodes {
            get {
                return ResourceManager.GetString("imdbPostfixEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /fullcredits?ref_=tt_cl_sm#cast.
        /// </summary>
        internal static string imdbPostfixFullCredits {
            get {
                return ResourceManager.GetString("imdbPostfixFullCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /plotsummary?ref_=tt_stry_pl.
        /// </summary>
        internal static string imdbPostfixSummary {
            get {
                return ResourceManager.GetString("imdbPostfixSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream open2 {
            get {
                return ResourceManager.GetStream("open2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ratingStars {
            get {
                object obj = ResourceManager.GetObject("ratingStars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ratingStarsSmall {
            get {
                object obj = ResourceManager.GetObject("ratingStarsSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redCross50p {
            get {
                object obj = ResourceManager.GetObject("redCross50p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveFromHDD {
            get {
                object obj = ResourceManager.GetObject("RemoveFromHDD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectForHDD {
            get {
                object obj = ResourceManager.GetObject("SelectForHDD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
