//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoKatalog.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int movieID { get; set; }
        public string customName { get; set; }
        public string originalName { get; set; }
        public System.DateTime addDate { get; set; }
        public int year { get; set; }
        public decimal rating { get; set; }
        public string internetLink { get; set; }
        public string trailerLink { get; set; }
        public string plot { get; set; }
        public long size { get; set; }
        public int runtime { get; set; }
        public string hddNum { get; set; }
        public int version { get; set; }
        public Nullable<byte> hasCroSub { get; set; }
        public Nullable<byte> hasEngSub { get; set; }
        public string cast { get; set; }
        public string director { get; set; }
        public string genres { get; set; }
    }
}
