//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoKatalog.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieEpisode
    {
        public int episodeID { get; set; }
        public string name { get; set; }
        public string origName { get; set; }
        public int seasonID { get; set; }
        public System.DateTime airDate { get; set; }
        public long size { get; set; }
        public int runtime { get; set; }
        public string hddID { get; set; }
        public string internetLink { get; set; }
        public byte version { get; set; }
        public Nullable<byte> hasCroSub { get; set; }
        public Nullable<byte> hasEngSub { get; set; }
    
        public virtual SerieSeason SerieSeason { get; set; }
    }
}
