//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoKatalog.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieSeason
    {
        public SerieSeason()
        {
            this.SerieEpisode = new HashSet<SerieEpisode>();
        }
    
        public int seasonID { get; set; }
        public int serieID { get; set; }
        public string name { get; set; }
        public string internetLink { get; set; }
        public string trailerLink { get; set; }
    
        public virtual Serie Serie { get; set; }
        public virtual ICollection<SerieEpisode> SerieEpisode { get; set; }
    }
}
