//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoKatalog.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public Serie()
        {
            this.SerieSeason = new HashSet<SerieSeason>();
        }
    
        public int serieID { get; set; }
        public string name { get; set; }
        public string origName { get; set; }
        public decimal rating { get; set; }
        public string internetLink { get; set; }
        public string summary { get; set; }
        public string trailerLink { get; set; }
        public string cast { get; set; }
        public string director { get; set; }
        public string genres { get; set; }
    
        public virtual ICollection<SerieSeason> SerieSeason { get; set; }
    }
}
