//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoKatalog.WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoDatabaseEntities : DbContext
    {
        public VideoDatabaseEntities()
            : base("name=VideoDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Movie> Movie { get; set; }
        public DbSet<Serie> Serie { get; set; }
        public DbSet<SerieEpisode> SerieEpisode { get; set; }
        public DbSet<SerieSeason> SerieSeason { get; set; }
    }
}
