//#region GLOBAL VARIABLES
// =========================================================================
//                              GLOBAL VARIABLES
// =========================================================================

var movieArray = new Array();
var movieArrayFiltered = new Array();
var movieFilter = new MovieFilter();
var selectedMovieGlobal;
var filterAttributeChanged = false;
var isFirstLoad = true;

//slider default values
var sizeStep = 5;
var sizeMin = 0;
var sizeMax = 50;

var runtimeStep = 10;
var runtimeMin = 0;
var runtimeMax = 300;


var ratingStep = 0.5;
var ratingMin = 1;
var ratingMax = 10;

var yearStep = 1;
var yearMin = 1950;
var yearMax = (new Date()).getFullYear();

// if orientation is supported (eg. mobile device) 
// instead of resize, do the orientation event
var supportsOrientationChange = 'onorientationchange' in window,
    orientationEvent = supportsOrientationChange ? 'orientationchange' : 'resize';
//#endregion

//#region FUNCTIONS
// =========================================================================
//                                FUNCTIONS
// =========================================================================

function Movie() {
	this.id = 0;
	this.name = '';
	this.origName = '';
	this.size = 0;
	this.rating = 0;
	this.cast = '';
	this.director = '';
	this.year = '';
	this.plot = '';
	this.hddNum = '';
	this.runtime = 0;
	this.hasCroSub = false;
	this.hasEngSub = false;
	this.videoRes = 0;
	this.dateAdded = new Date();
	this.imdbLink = '';
	this.trailerLink = '';
	this.genre = '';
	this.isSelected = false;
}
function MovieFilter() {
	this.name = '';
	this.cast = '';
	this.director = '';
	this.genre = new Array;
	this.minSize = 0;
	this.maxSize = 99;
	this.minYear = 0;
	this.maxYear = 9999;
	this.minRuntime = 0;
	this.maxRuntime = 9999;
	this.minRating = 0;
	this.maxRating = 10;
	this.hasCroSub = false;
	this.hasEngSub = false;
	this.sortProperty = 'addDate';
	this.addedAfterDate = new Date(1900, 1, 1, 0, 0, 0, 0);
	this.showSelected = false;
}

function checkForNewMovies() {
	$('#sideLoading').css('display', 'block');
	$.ajax({
		url: 'CheckForNewMovies',
		type: 'GET',		
		contentType: 'application/json; charset=utf-8',
		dataType: "text",
		cache: false,
		success: function (result) {
			$('#sideLoading').css('display', 'none');
			if (result == 1) {
				getMovies('#movieListBox');
			}
		},
		error: function(e) {

		}
	});
}
function getMovies(listboxID) {
	$('#mainLoading').css('display', 'block');
	$.ajax({
		url: 'allMoviesOrdered',
		type: "GET",
		data: {
			sortProperty: movieFilter.sortProperty
		},
		dataType: "text",
		async: true,
		cache: false,
		success: function (msg) {
			//return;
			if (msg.indexOf('<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->') > -1) {
				msg = msg.substring(0, msg.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->"));
			}
			var result = jQuery.parseJSON(msg);
			filterAttributeChanged = false;
			movieArray = jsonAsTextToMovieList(JSON.stringify(result.movies), true);
			$('#mainLoading').css('display', 'none');

			//initListBox();

			if (isFirstLoad) {
				filterMovies('#movieListBox');
				movieFilter.showSelected = true;
				filterMovies('#selectedMovieListBox');
				movieFilter.showSelected = false;
			}
			else {
				filterMovies(listboxID);
			}
			//$("#reloadIndicator").css("display", "none");
			//$("#reloadDiv").css("display", "none");
			//$("#miniReloadDiv").css("display", "none");
			//$("#labelCount").html(movies.length);
			checkForNewMovies();
			downloadMoviePosters();
		},
		error: function (e) {
		    $('body').html(e.responseText);
			//alert('error');
			//$("#reloadIndicator").css("display", "none");
			//$("#miniReloadDiv").css("display", "none");
			//$("#reloadDiv").css("display", "none");
			//$("#labelCount").html(movies.length);
		}
	});
}
function jsonAsTextToMovieList(text, isFullJson) {
	var result = jQuery.parseJSON(text);
	if (result.length == 0) {
		return;
	}
	var newMovies = new Array();
	for (var i = 0; i < result.length; i++) {
		newMovies.push(jsonToMovie(result[i], true));
	}

	//for (var i = 0; i < movieArray.length; i++) {
	//    newMovies[newMovies.length] = movieArray[i];
	//}
	//movieArray = newMovies;
	//localStorage.setItem("movieList", JSON.stringify(movieArray));
	return newMovies;
}
function jsonToMovie(jsonMovie, isFromServer) {
	var newMovie = new Movie();

	newMovie.id = jsonMovie.id;
	newMovie.name = jsonMovie.name;
	newMovie.origName = jsonMovie.origName;
	newMovie.size = jsonMovie.size;
	newMovie.rating = jsonMovie.rating;
	newMovie.plot = jsonMovie.plot;
	newMovie.year = jsonMovie.year;
	newMovie.runtime = jsonMovie.runtime;
	newMovie.videoRes = jsonMovie.videoRes;
	newMovie.dateAdded = new Date(jsonMovie.dateAdded.toString());
	newMovie.imdbLink = jsonMovie.imdbLink;
	newMovie.trailerLink = jsonMovie.trailerLink;
	newMovie.hddNum = jsonMovie.hddNum;
	newMovie.cast = jsonMovie.cast;
	newMovie.director = jsonMovie.director;
	newMovie.genre = jsonMovie.genres;
	newMovie.hasCroSub = jsonMovie.hasCroSub;
	newMovie.hasEngSub = jsonMovie.hasEngSub;
	return newMovie;
}

function initListBox() {
	$("#movieListBox").jqxListBox({
		source: new Array(),
		width: $('#listboxDiv').width(),
		height: $('#listboxDiv').height() - $('#listSearch').height() - 20,
		displayMember: 'name',
		valueMember: 'id',
		selectedIndex: -1,
		itemHeight: 40,
		theme: 'metrodark'
	});
	$("#movieListBox").on('change', function (event) {
		if (event.args) {
			var item = event.args.item;
			if (item) {
				changeMovieInfo(item.value, event.args.index);
			}
		}
	});
	$("#selectedMovieListBox").jqxListBox({
	    source: new Array(),
	    width: $('#listboxDiv').width(),
	    height: $('#listboxDiv').height() - $('#listSearch').height() - 20,
	    displayMember: 'name',
	    valueMember: 'id',
	    selectedIndex: -1,
	    itemHeight: 40,
	    //theme: 'metrodark'
	});
	$("#selectedMovieListBox").on('change', function (event) {
	    if (event.args) {
	        var item = event.args.item;
	        if (item) {
	            changeMovieInfo(item.value, event.args.index);
	        }
	    }
	});
}

function filterMovies(listBoxID) {
    $(listBoxID).jqxListBox('beginUpdate');
	if (filterAttributeChanged) {
		getMovies(listBoxID);
		return;
	}
	$(listBoxID).jqxListBox('clear');
	//movieArrayFiltered = new Array();
	for (var i = 0; i < movieArray.length; i++) {
		//if (isFirstLoad && isMovieSelected(movieArray[i].id)) {
		//	selectedHDD.sizeSelected += movieArray[i].size;
		//}
		//naziv
		if (movieFilter.name.length > 0 && movieArray[i].name.trim().toLowerCase().indexOf(movieFilter.name.trim().toLowerCase()) < 0)
			continue;
		//velicina
		if (movieFilter.minSize > (movieArray[i].size / (1024 * 1024 * 1024)) ||
			movieFilter.maxSize < (movieArray[i].size / (1024 * 1024 * 1024)))
			continue;
		//trajanje
		if (movieFilter.minRuntime > (movieArray[i].runtime / (1000 * 60)) ||
			movieFilter.maxRuntime < ((movieArray[i].runtime / (1000 * 60))))
			continue;
		//ocjena
		if (movieFilter.minRating > movieArray[i].rating || movieFilter.maxRating < movieArray[i].rating)
			continue;
		//godina
		if (movieFilter.minYear > movieArray[i].year || movieFilter.maxYear < movieArray[i].year)
			continue;
		//datum dodavanja
		if (movieArray[i].dateAdded < movieFilter.addedAfterDate)
			continue;
		//odabrano / neodabrano
		if ((movieFilter.showSelected && isMovieSelected(movieArray[i].id) == false) ||
			(movieFilter.showSelected == false && isMovieSelected(movieArray[i].id)))
			continue;
		//hrv titlovi
		if (movieFilter.hasCroSub && movieArray[i].hasCroSub == false) {
			continue;
		}
		//eng titlovi
		if (movieFilter.hasEngSub && movieArray[i].hasEngSub == false) {
			continue;
		}
		//zanrovi
		var hasGenre = false;
		for (var j = 0; j < movieFilter.genre.length; j++) {
			if (movieArray[i].genre.trim().toLowerCase().indexOf(movieFilter.genre[j].trim().toLowerCase()) >= 0) {
				hasGenre = true;
				break;
			}
		}
		if (!hasGenre && movieFilter.genre.length > 0) {
			continue;
		}

	    //movieArrayFiltered.push(movieArray[i]);
		$(listBoxID).jqxListBox('addItem', movieArray[i]);
	}
	if (isFirstLoad) {
		updatePercentage();
	}
	$(listBoxID).jqxListBox('endUpdate');
	isFirstLoad = false;
}
function changeMovieInfo(selectedMovieID, listIndex) {
	//alert("changed");
	//if (selectedMovieGlobal != null && selectedMovieGlobal.id == selectedMovie.id && selectedMovieGlobal.full == true)
	//	return;
    selectedMovieGlobal = getMovieWithId(selectedMovieID);
    var posterLink = "https://hddpunjenje.000webhostapp.com/posters/movie/" + selectedMovieGlobal.name.replace("&#39;", "'").replace("&amp;", "&") + ".jpg";
	var replaced = true;
	while (replaced) {
	    replaced = false;
	    if (posterLink.indexOf("'") >= 0) {
	        posterLink = posterLink.replace("'", '%27');
	        replaced = true;
	    }
	}
	$('#loadingPosterIndicator').css('display', 'block');
	$('#moviePoster').css('display', 'none');
	//$('#moviePoster').css('background-image', "url('" + posterLink + "')");
	$.ajax({
		url: posterLink,
		type: "GET",
		cache: true,
		processData: false,
	}).always(function () {
		$('#moviePoster').css('background-image', "url('" + posterLink + "')");
		$('#moviePoster').css('display', 'block');
		$('#loadingPosterIndicator').css('display', 'none');
	});

	$('#movieName').html("");
	$('#movieYear').html("");
	$('#ratingText').html("");
	$('#cast').html("");
	$('#director').html("");
	$('#plot').html("");
	$('#runtime').html("");
	$('#size').html("");
	$('#genres').html("");
	$('#movieYear').prop('title', '');

	$('#movieName').html(selectedMovieGlobal.name);
	$('#movieYear').html(selectedMovieGlobal.year);
	$('#ratingText').html(selectedMovieGlobal.rating.toFixed(1));
	$('#cast').html(selectedMovieGlobal.cast);
	$('#director').html(selectedMovieGlobal.director);
	$('#plot').html(removeHyperlinks(selectedMovieGlobal.plot));
	$('#runtime').html(getRuntimeInText(selectedMovieGlobal.runtime));
	$('#size').html(getSize(selectedMovieGlobal.size).toFixed(2) + " GB");
	$('#genres').html(selectedMovieGlobal.genre);
	$('#movieYear').prop('title', selectedMovieGlobal.hddNum);
	$('#moviePoster').css('display', "block");

	$('#croSubIcon').addClass('noSub');
	$('#croSubIcon').removeClass('hasSub');
	$('#engSubIcon').addClass('noSub');
	$('#engSubIcon').removeClass('hasSub');

	if (selectedMovieGlobal.hasCroSub) {
		$('#croSubIcon').addClass('hasSub');
		$('#croSubIcon').removeClass('noSub');
	}
	if (selectedMovieGlobal.hasEngSub) {
		$('#engSubIcon').addClass('hasSub');
		$('#engSubIcon').removeClass('noSub');
	}

	//var youtubeID = selectedMovieGlobal.trailerLink.substring(selectedMovieGlobal.trailerLink.indexOf("?v=") + 3);
	//document.getElementById("trailerFrame").src = "http://www.youtube.com/embed/" + youtubeID;
}
function getMovieWithId(movieID) {
	for (var i = 0; i < movieArray.length; i++) {
		if (movieArray[i].id == movieID) {
			return movieArray[i];
		}
	}
	return new Movie();
}
function isMovieSelected(movieID) {
	if (selectedMovieIdArray.indexOf(movieID) >= 0)
		return true;
	else
		return false;
}

function downloadMoviePosters(index) {
	imgArray = new Array();

	var img = new Image();
    var posterLink = "https://hddpunjenje.000webhostapp.com/posters/movie/" + movieArray[index].name.replace("&#39;", "'").replace("&amp;", "&") + ".jpg";
	img.src = posterLink;
	imgArray.push(img);

	setTimeout(function () {
		if (index < 50) {
			downloadMoviePosters(index++);
		}
	}, 100);

}


// ============================================================
//                          MAIN RESIZE
// ============================================================
function resize() {
	var windowWidth = $(window).width(); //retrieve current window width
	var windowHeight = $(window).height();
	$('#resolution').html(windowWidth + ' x ' + windowHeight + ' (' + formatFloat(windowWidth / windowHeight, 2) + ')');
	//initListBox();
	initInput();
	var width = $('#listboxDiv').width();
	var height = $('#listboxDiv').height() - $('#listSearch').height() - 20;
	//$("#movieListBox").width(width);
	//$("#movieListBox").height(height);
	//$("#listBoxContentmovieListBox").width(width);
	//$("#listBoxContentmovieListBox").height(height);
	//$("#listBoxContentmovieListBox>div").width(width);
	//$("#listBoxContentmovieListBox>div").height(height);
	////vertical scroll bar
	////$('#verticalScrollBarmovieListBox').height(height);
	//$('#verticalScrollBarmovieListBox').css('left', width - 20 + 'px');
	////$('#jqxScrollBtnDownverticalScrollBarmovieListBox').css('top', height - 15 + 'px');
	//$('#jqxScrollAreaDownverticalScrollBarmovieListBox').css('height', height - 60 + 'px');
	////horizontal scroll bar);
	$('#horizontalScrollBarmovieListBox').css('display', 'none');
	$('#bottomRightmovieListBox').css('display', 'none');
	////$('#horizontalScrollBarmovieListBox').width(width);
	////$('#horizontalScrollBarmovieListBox').css('top', height - 20 + 'px');
}

//#endregion

//#region EVENT HANDLERS
// =========================================================================
//                             EVENT HANDLERS
// =========================================================================

function addButtonClick() {
    var selectedMovieID = 0;    
    var selectedIndex = 0;

    selectedMovieID = $("#movieListBox").jqxListBox('getSelectedItems')[0].value;
    selectedIndex = $("#movieListBox").jqxListBox('getSelectedIndex');
    $("#selectedMovieListBox").jqxListBox('addItem', $("#movieListBox").jqxListBox('getSelectedItem'));
    $("#movieListBox").jqxListBox('removeAt', $("#movieListBox").jqxListBox('getSelectedIndex'));

    if ($("#movieListBox").jqxListBox('getSelectedItems')[0] != null) {
    	changeMovieInfo($("#movieListBox").jqxListBox('getSelectedItems')[0].value, selectedIndex);
    }
    else {
    	$("#movieListBox").jqxListBox('selectIndex', selectedIndex - 1);
    }

    var fullMovie = getMovieWithId(selectedMovieID);
    selectedHDD.sizeSelected += fullMovie.size;
    selectedMovieIdArray.push(fullMovie.id);
	
	
	updatePercentage(true);
	localStorage.setItem('selectedMoviesID', JSON.stringify(selectedMovieIdArray));
}
function removeButtonClick() {
    var selectedMovieID = 0;
    var selectedIndex = 0;

    selectedMovieID = $("#selectedMovieListBox").jqxListBox('getSelectedItems')[0].value;
    selectedIndex = $("#selectedMovieListBox").jqxListBox('getSelectedIndex');
    $("#movieListBox").jqxListBox('addItem', $("#selectedMovieListBox").jqxListBox('getSelectedItem'));
    $("#selectedMovieListBox").jqxListBox('removeAt', $("#selectedMovieListBox").jqxListBox('getSelectedIndex'));

    if ($("#selectedMovieListBox").jqxListBox('getSelectedItems')[0] != null) {
        changeMovieInfo($("#selectedMovieListBox").jqxListBox('getSelectedItems')[0].value, selectedIndex);
    }
    else {
        $("#selectedMovieListBox").jqxListBox('selectIndex', selectedIndex - 1);
    }

    var fullMovie = getMovieWithId(selectedMovieID);
    selectedHDD.sizeSelected -= fullMovie.size;
    selectedMovieIdArray.splice(selectedMovieIdArray.indexOf(fullMovie.id), 1);

    updatePercentage();
    localStorage.setItem('selectedMoviesID', JSON.stringify(selectedMovieIdArray));
}
function showSelectedButtonClick() {
    movieFilter.showSelected = !movieFilter.showSelected;
    if (movieFilter.showSelected) {
        //if ($("#selectedMovieListBox").jqxListBox('getItems').length < selectedMovieIdArray.length) {
        //    filterMovies("#selectedMovieListBox");
        //}
        $('#addButton').css('display', 'none');
        $('#removeButton').css('display', 'block');

		$('#showSelectedButton').html('NEODABRANO');
		$('#movieListBox').css('display', 'none');
		$('#selectedMovieListBox').css('display', 'block');
    	try {
    		changeMovieInfo($("#selectedMovieListBox").jqxListBox('getSelectedItems')[0].value,
			$("#selectedMovieListBox").jqxListBox('getSelectedIndex'));
    	}
    	catch (error) {
    		changeMovieInfo(new Movie(), -1);
    	}
		
	}
    else {
        $('#addButton').css('display', 'block');
        $('#removeButton').css('display', 'none');
		
		$('#showSelectedButton').html('ODABRANO');
		$('#selectedMovieListBox').css('display', 'none');
		$('#movieListBox').css('display', 'block');
    	try {
    		changeMovieInfo($("#movieListBox").jqxListBox('getSelectedItems')[0].value,
			$("#movieListBox").jqxListBox('getSelectedIndex'));
    	}
    	catch (error) {
    		changeMovieInfo(new Movie(), -1);
    	}
		
	}
	//initListBox();
}

//#endregion

//#region ON LOAD
// =========================================================================
//                                  ON LOAD
// =========================================================================
$(function () {
	$('#imdbIcon').click(function () {
		if (selectedMovieGlobal != null) {
			window.open(selectedMovieGlobal.imdbLink, '_blank');
		}
	});
	$('#trailerIcon').click(function () {
		if (selectedMovieGlobal != null) {
			var youtubeID = selectedMovieGlobal.trailerLink.substring(selectedMovieGlobal.trailerLink.indexOf("?v=") + 3);
			document.getElementById("trailerFrame").src = "http://www.youtube.com/embed/" + youtubeID;

			$('#trailerWindow').css('display', 'block');
			$('#trailerWindowContent').jqxWindow('open');
		}
	});
	$('#trailerWindow').on('close', function (event) {
		document.getElementById("trailerFrame").src = "";
	});
	$('#addButton').click(function () {
		addButtonClick();
	});
	$('#removeButton').click(function () {
	    removeButtonClick();
	});
	//$('#filters2').css('display', 'none');
	$('#showSelectedButton').click(function () {
		showSelectedButtonClick();
	});
	initInput();
	initFilterContent();

	if (localStorage.getItem('movieFilter') != null) {
		//movieFilter = JSON.parse(sessionStorage.getItem('movieFilter'));
		//movieFilter.name = '';
	}
	$('#filters2').css('display', 'none');
	initListBox();
	getMovies('#movieListBox');
	$("#movieListBox").keyup(function (event) {
	    if (event.keyCode == 13) {
	        addButtonClick();
	    }
	});
	$("#selectedMovieListBox").keyup(function (event) {
	    if (event.keyCode == 13) {
	        removeButtonClick();
	    }
	});
})
function initFilterContent() {
	$("#selectGenre").multiselect({
		buttonWidth: $('#selectGenreDiv').width(),
		buttonText: function (options, select) {
			if (options.length == 0) {
				return "Odaberi zanrove" + ' <b class="caret"></b>';
			}
			else {
				if (options.length > 3) {
					return options.length + " odabrano" + ' <b class="caret"></b>';
				}
				else {
					var selected = '';
					options.each(function () {
						var label = ($(this).attr('label') !== undefined) ? $(this).attr('label') : $(this).html();
						selected += label + ', ';
					});
					return selected.substr(0, selected.length - 2) + ' <b class="caret"></b>';
				}
			}

		},
		onChange: function (option, checked) {
			var genre = option.context.id;
			if (checked) {
				movieFilter.genre.push(genre);
			}
			else {
				if (movieFilter.genre.indexOf(genre) >= 0) {
					movieFilter.genre.splice(movieFilter.genre.indexOf(genre), 1);
				}
			}
		},
		maxHeight: $('#filters2').height()
	});
	$("#sortSelectProperty").multiselect({
		buttonWidth: $('#sortSelectContent').width(),
		buttonText: function (options, select) {
			if (options.length == 0) {
				return "Odaberi atribut za sortiranje" + ' <b class="caret"></b>';
			}
			else {
				if (options.length > 3) {
					return options.length + " odabrano" + ' <b class="caret"></b>';
				}
				else {
					var selected = '';
					options.each(function () {
						var label = ($(this).attr('label') !== undefined) ? $(this).attr('label') : $(this).html();

						selected += label + ', ';
					});
					return selected.substr(0, selected.length - 2) + ' <b class="caret"></b>';
				}
			}
		},
		maxHeight: $('#filters2').height(),
		onChange: function (option, checked) {
			var sortProp = option.context.value;
			movieFilter.sortProperty = sortProp;
			filterAttributeChanged = true;
		},

	});
	$("#afterDatePicker").jqxDateTimeInput({
		width: $('#afterDatePickerContent').width() * 0.87,
		height: $('#afterDatePickerContent').height() * 0.5,
		dropDownHorizontalAlignment: 'right',
		value: dateLastVisited,
		firstDayOfWeek: 1
	});
	$('#afterDatePicker').on('valuechanged', function (event) {
	    movieFilter.addedAfterDate = event.args.date;
	    $('#inputafterDatePicker').css('display', 'block');
	    
	});
	//$('#afterDatePicker').jqxDateTimeInput('setDate', null);
	movieFilter.addedAfterDate = null;

	$('#hasCroSubFilterCheckbox').iCheck({
		checkboxClass: 'icheckbox_polaris',
		radioClass: 'iradio_futurico',
		increaseArea: '20%' // optional
	});
	$('#hasCroSubFilterCheckbox').on('ifChecked', function (event) {
		movieFilter.hasCroSub = true;
	});

	$('#hasCroSubFilterCheckbox').on('ifUnchecked', function (event) {
		movieFilter.hasCroSub = false;
	});


	$('#hasEngSubFilterCheckbox').iCheck({
		checkboxClass: 'icheckbox_polaris',
		radioClass: 'iradio_futurico',
		increaseArea: '20%' // optional
	});
	$('#hasEngSubFilterCheckbox').on('ifChecked', function (event) {
		movieFilter.hasEngSub = true;
	});

	$('#hasEngSubFilterCheckbox').on('ifUnchecked', function (event) {
		movieFilter.hasEngSub = false;
	});

	$('#applyFiltersButton').click(function () {
		localStorage.setItem('movieFilter', JSON.stringify(movieFilter));
		if (dateLastVisited != null) {
			//movieFilter.addedAfterDate = dateLastVisited;
		}
		if (movieFilter.showSelected) {
		    filterMovies("#selectedMovieListBox");
		}
		else {
		    filterMovies("#movieListBox");
		}
	});
	//$('#selectGenreDiv input').iCheck({
	//	checkboxClass: 'icheckbox_polaris',
	//	radioClass: 'iradio_futurico',
	//	increaseArea: '20%' // optional
	//});	
	$('#resetFiltersButton').click(function () {
		$("#ratingSlider").val([ratingMin, ratingMax]);
		$("#sizeSlider").val([sizeMin, sizeMax]);
		$("#runtimeSlider").val([runtimeMin, runtimeMax]);
		$("#yearSlider").val([yearMin, yearMax]);
		$('option', $("#selectGenre")).each(function (element) {
			$("#selectGenre").multiselect('deselect', $(this).val());
		});
		movieFilter.genre = new Array();
		$('option', $("#sortSelectProperty")).each(function (element) {
			$("#sortSelectProperty").multiselect('deselect', $(this).val());
		});
		movieFilter.sortProperty = 'addDate';
		filterAttributeChanged = true;
		$('#hasCroSubFilterCheckbox').iCheck('uncheck');
		$('#hasEngSubFilterCheckbox').iCheck('uncheck');
		$('#afterDatePicker').jqxDateTimeInput('setDate', null);
		movieFilter.addedAfterDate = null;

		$("#imdbMinLabel").html($("#ratingSlider").val()[0].substring(0, $("#ratingSlider").val()[0].length - 1));
		$("#imdbMaxLabel").html($("#ratingSlider").val()[1].substring(0, $("#ratingSlider").val()[1].length - 1));
		movieFilter.minRating = $("#ratingSlider").val()[0];
		movieFilter.maxRating = $("#ratingSlider").val()[1];
		$("#sizeMinLabel").html($("#sizeSlider").val()[0].substring(0, $("#sizeSlider").val()[0].length - 1));
		$("#sizeMaxLabel").html($("#sizeSlider").val()[1].substring(0, $("#sizeSlider").val()[1].length - 1));
		movieFilter.minSize = $("#sizeSlider").val()[0];
		movieFilter.maxSize = $("#sizeSlider").val()[1];
		$("#runtimeMinLabel").html($("#runtimeSlider").val()[0].substring(0, $("#runtimeSlider").val()[0].length - 3));
		$("#runtimeMaxLabel").html($("#runtimeSlider").val()[1].substring(0, $("#runtimeSlider").val()[1].length - 3));
		movieFilter.minRuntime = $("#runtimeSlider").val()[0];
		movieFilter.maxRuntime = $("#runtimeSlider").val()[1];
		$("#yearMinLabel").html($("#yearSlider").val()[0].substring(0, $("#yearSlider").val()[0].length - 3));
		$("#yearMaxLabel").html($("#yearSlider").val()[1].substring(0, $("#yearSlider").val()[1].length - 3));
		movieFilter.minYear = $("#yearSlider").val()[0];
		movieFilter.maxYear = $("#yearSlider").val()[1];
	});
	initSliders();
}
function initSliders() {
    //return;
	$("#ratingSlider").noUiSlider({
		start: [1, 10],
		connect: true,
		range: {
			'min': 1,
			'max': 10
		}
	});
	$("#ratingSlider").on({
		slide: function () {
			$("#imdbMinLabel").html($("#ratingSlider").val()[0].substring(0, $("#ratingSlider").val()[0].length - 1));
			$("#imdbMaxLabel").html($("#ratingSlider").val()[1].substring(0, $("#ratingSlider").val()[1].length - 1));
			movieFilter.minRating = $("#ratingSlider").val()[0];
			movieFilter.maxRating = $("#ratingSlider").val()[1];
		}
	});


	$("#sizeSlider").noUiSlider({
		start: [0, 50],
		connect: true,
		range: {
			'min': 0,
			'max': 50
		}
	});
	$("#sizeSlider").on({
		slide: function () {
			$("#sizeMinLabel").html($("#sizeSlider").val()[0].substring(0, $("#sizeSlider").val()[0].length - 1));
			$("#sizeMaxLabel").html($("#sizeSlider").val()[1].substring(0, $("#sizeSlider").val()[1].length - 1));
			movieFilter.minSize = $("#sizeSlider").val()[0];
			movieFilter.maxSize = $("#sizeSlider").val()[1];
		}
	});


	$("#runtimeSlider").noUiSlider({
		start: [0, 300],
		connect: true,
		range: {
			'min': 0,
			'max': 300
		}
	});
	$("#runtimeSlider").on({
		slide: function () {
			$("#runtimeMinLabel").html($("#runtimeSlider").val()[0].substring(0, $("#runtimeSlider").val()[0].length - 3));
			$("#runtimeMaxLabel").html($("#runtimeSlider").val()[1].substring(0, $("#runtimeSlider").val()[1].length - 3));
			movieFilter.minRuntime = $("#runtimeSlider").val()[0];
			movieFilter.maxRuntime = $("#runtimeSlider").val()[1];
		}
	});


	$("#yearSlider").noUiSlider({
		start: [1950, (new Date()).getFullYear()],
		connect: true,
		range: {
			'min': 1950,
			'max': (new Date()).getFullYear()
		}
	});
	$("#yearSlider").on({
		slide: function () {
			$("#yearMinLabel").html($("#yearSlider").val()[0].substring(0, $("#yearSlider").val()[0].length - 3));
			$("#yearMaxLabel").html($("#yearSlider").val()[1].substring(0, $("#yearSlider").val()[1].length - 3));
			movieFilter.minYear = $("#yearSlider").val()[0];
			movieFilter.maxYear = $("#yearSlider").val()[1];
		}
	});
}
function initInput() {
	$("#listSearch").jqxInput({
		placeHolder: "Pretraži filmove...",
		height: 40,
		width: $('#listboxDiv').width() - ($('#listboxDiv').width() * 0.02)
	});
	$('#listSearch').keyup(function () {
	    movieFilter.name = $('#listSearch').val();
	    if (movieFilter.showSelected) {
	        filterMovies("#selectedMovieListBox");
	    }
	    else {
	        filterMovies("#movieListBox");
	    }
	});
}



//#endregion

//#region FUNCTION AND EVENT BINDING
// =========================================================================
//                         FUNCTION AND EVENT BINDING
// =========================================================================
if (!window.addEventListener) {
	window.attachEvent('onresize', function () {
		resize();
	});
}
else {
	window.addEventListener(orientationEvent, function () {
		resize();
	}, false);
}

window.onload = function () {
	resize();
}

//#endregion

